// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgxu1OoK_0cSwnF2AiLqLdElUoy2A3-vk',
    appId: '1:219193020521:web:60fe496b3e44a1507992f8',
    messagingSenderId: '219193020521',
    projectId: 'reportinternshipmobile',
    authDomain: 'reportinternshipmobile.firebaseapp.com',
    storageBucket: 'reportinternshipmobile.firebasestorage.app',
    measurementId: 'G-TBG4RC72K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy5CiXU8s-i7dklhzr_zFUd8TsrFU6gpw',
    appId: '1:219193020521:android:b0f4841cfa8a8a337992f8',
    messagingSenderId: '219193020521',
    projectId: 'reportinternshipmobile',
    storageBucket: 'reportinternshipmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCutLoM0TWnV03v7EoeOsFw7AZ-lpDSI5k',
    appId: '1:219193020521:ios:5426ba56332ce9fd7992f8',
    messagingSenderId: '219193020521',
    projectId: 'reportinternshipmobile',
    storageBucket: 'reportinternshipmobile.firebasestorage.app',
    iosBundleId: 'com.example.reportInternship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCutLoM0TWnV03v7EoeOsFw7AZ-lpDSI5k',
    appId: '1:219193020521:ios:5426ba56332ce9fd7992f8',
    messagingSenderId: '219193020521',
    projectId: 'reportinternshipmobile',
    storageBucket: 'reportinternshipmobile.firebasestorage.app',
    iosBundleId: 'com.example.reportInternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgxu1OoK_0cSwnF2AiLqLdElUoy2A3-vk',
    appId: '1:219193020521:web:a4c27514b015b2f47992f8',
    messagingSenderId: '219193020521',
    projectId: 'reportinternshipmobile',
    authDomain: 'reportinternshipmobile.firebaseapp.com',
    storageBucket: 'reportinternshipmobile.firebasestorage.app',
    measurementId: 'G-26BJKVEM5B',
  );
}
